version: "3.8"

services:
  mysql:
    image: mysql:8.0.26
    container_name: quivi_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    network_mode: host
    ports:
      - "5432:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
